version: '3.7'

services:
    db:
        image: postgres
        container_name: test_api_postgress
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: django_db
        ports:
            - "54321:5432"
    web:
        build: .
        volumes:
            - .:/usr/src/test_api
        ports:
            - "8000:8000"
        depends_on:
            - db

